name:                Neopolitan
version:             0.1.0.0
github:              "CristhianMotoche/Neopolitan"
license:             BSD3
author:              "CristhianMotoche"
maintainer:          "cristhian.motoche@gmail.com"
copyright:           "WTFPL"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/CristhianMotoche/Neopolitan#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson >= 1.4 && < 1.5
    - bytestring
    - http-client >= 0.6.4 && < 0.7
    - http-client-tls >= 0.3 && < 0.4

executables:
  neo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Neopolitan

tests:
  Neopolitan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Neopolitan
    - aeson
    - base >= 4.9
    - bytestring
    - tasty >= 1.2 && < 1.3
    - tasty-hunit >= 0.10 && < 0.11
